/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DoToMarkdownPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DoToMarkdownPlugin = class extends import_obsidian.Plugin {
  async onload() {
    super.onload();
    this.registerExtensions(["do"], "markdown");
  }
  onunload() {
  }
};
//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsibWFpbi50cyJdLAogICJzb3VyY2VzQ29udGVudCI6IFsiaW1wb3J0IHsgQXBwLCBFZGl0b3IsIE1hcmtkb3duVmlldywgTW9kYWwsIE5vdGljZSwgUGx1Z2luLCBQbHVnaW5TZXR0aW5nVGFiLCBTZXR0aW5nIH0gZnJvbSAnb2JzaWRpYW4nO1xuXG5cblxuXG5leHBvcnQgZGVmYXVsdCBjbGFzcyBEb1RvTWFya2Rvd25QbHVnaW4gZXh0ZW5kcyBQbHVnaW4ge1xuXG5cdGFzeW5jIG9ubG9hZCgpIHtcblx0XHRzdXBlci5vbmxvYWQoKTtcblx0XHRcblx0XHR0aGlzLnJlZ2lzdGVyRXh0ZW5zaW9ucyhbXCJkb1wiXSwgXCJtYXJrZG93blwiKTtcblx0fVxuXG5cdG9udW5sb2FkKCkge1xuXG5cdH1cbn1cbiJdLAogICJtYXBwaW5ncyI6ICI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQSxzQkFBNEY7QUFLNUYsSUFBcUIscUJBQXJCLGNBQWdELHVCQUFPO0FBQUEsRUFFdEQsTUFBTSxTQUFTO0FBQ2QsVUFBTSxPQUFPO0FBRWIsU0FBSyxtQkFBbUIsQ0FBQyxJQUFJLEdBQUcsVUFBVTtBQUFBLEVBQzNDO0FBQUEsRUFFQSxXQUFXO0FBQUEsRUFFWDtBQUNEOyIsCiAgIm5hbWVzIjogW10KfQo=
